spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: be-better
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT_EXTERNAL}/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false
    enabled: true
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INTERNAL}/realms/${KEYCLOAK_APPLICATION_REALM}
          jwk-set-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INTERNAL}/realms/${KEYCLOAK_APPLICATION_REALM}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: http://keycloak:8080/login/oauth2/code/keycloak
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INTERNAL}/realms/${KEYCLOAK_APPLICATION_REALM}
  keycloak:
    uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INTERNAL}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${BROKER_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080

mail:
  domain: "https://worksolutions.ru/"
  notification-sender: "no-reply@be-better.ru"

keycloak-initializer:
  masterRealm: ${KEYCLOAK_MASTER_REALM}
  applicationRealm: ${KEYCLOAK_APPLICATION_REALM}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_ADMIN}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  url: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INTERNAL}/

minio:
  minio-user: ${MINIO_ROOT_USER}
  minio-password: ${MINIO_ROOT_PASSWORD}
  minio-endpoint: ${MINIO_ENDPOINT}
  minio-bucketName: ${MINIO_BUCKET_NAME}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
