###### Сценарий - восстановить доступ

##### Подготовительная часть

### Регистрация нового пользователя
POST http://{{host}}:{{port}}/api/v1/auth/register/
Content-Type: application/json

{
  "email": "recovery@mail.ru",
  "password": "Admin123456!",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "company": {
    "companyTitle": "Company",
    "inn": "100000000004"
  }
}

##### КЕЙС №1 успешное восстановление доступа

#### Пользователь корректно устанавливает новый пароль и авторизуется в системе

### Запрос на восстановление/установку пароля, получения ссылки для установки нового пароля
POST http://{{host}}:{{port}}/api/v1/auth/password-recovery/
Content-Type: application/json

{
  "login": "recovery@mail.ru"
}

### Установка нового пароля при переходе по ссылке для установки нового пароля
POST http://{{host}}:{{port}}/api/v1/auth/reset-password/
Content-Type: application/json

{
  "login": "recovery@mail.ru",
  "secret": "81461c2e-8e9f-488b-bd09-d278871829d2",
  "newPassword": "Admin654321!"
}

### Проверка - успешная аутентификация пользователя с новым паролем
POST http://{{host}}:{{port}}/api/v1/auth/login/
Content-Type: application/json

{
  "login": "recovery@mail.ru",
  "password": "Admin654321!"
}

##### КЕЙС №2 восстановление доступа с некорректным значением логина

#### Пользователь с незарегистрированным в системе логином не может восстановить доступ, при попытке восстановить
#### доступ система должна вернуть ошибочный ответ с кодом 401

### Запрос на восстановление/установку пароля, получения ссылки для установки нового пароля
POST http://{{host}}:{{port}}/api/v1/auth/password-recovery/
Content-Type: application/json

{
  "login": "recovery1@mail.ru"
}

### Установка нового пароля при переходе по ссылке для установки нового пароля - 401 ответ
POST http://{{host}}:{{port}}/api/v1/auth/reset-password/
Content-Type: application/json

{
  "login": "recovery1@mail.ru",
  "secret": "64c185a4-f4a6-4093-acf5-d386710c5c9c",
  "newPassword": "Admin654321!1"
}

##### КЕЙС №3 восстановление доступа с некорректным значением нового пароля

#### Пользователь при указании некорректного нового пароля не может восстановить доступ, при попытке восстановить
#### доступ система должна вернуть ошибочный ответ с кодом 400

### Запрос на восстановление/установку пароля, получения ссылки для установки нового пароля
POST http://{{host}}:{{port}}/api/v1/auth/password-recovery/
Content-Type: application/json

{
  "login": "recovery@mail.ru"
}

### Установка нового пароля при переходе по ссылке для установки нового пароля -
### 400 ответ "Field 'newPassword': Password must contain at least one letter, one digit, and one special character."
POST http://{{host}}:{{port}}/api/v1/auth/reset-password/
Content-Type: application/json

{
  "login": "recovery1@mail.ru",
  "secret": "0b4d7d19-17d7-4289-920b-de2ef9d9dd61",
  "newPassword": "12345678"
}

##### КЕЙС №4 восстановление доступа заблокированного пользователя

#### Заблокированный пользователь не может восстановить доступ, при попытке восстановить
#### доступ система должна вернуть ошибочный ответ с кодом 400

### Регистрация нового пользователя
POST http://{{host}}:{{port}}/api/v1/auth/register/
Content-Type: application/json

{
  "email": "blockuser@mail.ru",
  "password": "Admin123456!",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "company": {
    "companyTitle": "Company",
    "inn": "100000000005"
  }
}

### Аутентификация ранее зарегистрированного пользователя с ролью методолога
POST http://{{host}}:{{port}}/api/v1/auth/login/
Content-Type: application/json

{
  "login": "recovery@mail.ru",
  "password": "Admin654321!"
}

### Установка активной роли методолога для возможности блокировки пользователя
POST http://{{host}}:{{port}}/api/v1/user-profiles/set-active-role/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "activeRole": "METHODOLOGIST"
}

### Блокировка пользователя
POST http://{{host}}:{{port}}/api/v1/users/5/block/
Authorization: Bearer {{authToken}}

### Запрос на восстановление/установку пароля, получения ссылки для установки нового пароля
POST http://{{host}}:{{port}}/api/v1/auth/password-recovery/
Content-Type: application/json

{
  "login": "blockuser@mail.ru"
}

### Установка нового пароля при переходе по ссылке для установки нового пароля - ошибка код 400
POST http://{{host}}:{{port}}/api/v1/auth/reset-password/
Content-Type: application/json

{
  "login": "blockuser@mail.ru",
  "secret": "ba488df3-581e-48a6-9f59-d418ba6b01c5",
  "newPassword": "Admin123456!1"
}